Lesson3
kostenkoSergei/geekshop pull request #3
Opened 2021-01-27 18:26 UTC by kostenkoSergei

lesson 3 homework

2021-01-28 13:43 UTC, Vokler requested changes

2021-01-28 13:43 UTC, Vokler commented on mainapp/views.py
> +        'title': ProductCategory.objects.get(pk=pk)
А почему у вас title - это объект из модели?)

2021-01-28 13:48 UTC, kostenkoSergei commented
Потому что функция category у меня отображается конкретную категорию.а так как у нас в модели ProductCategory есть метод __str__, то он возвратит ее name. В итоге я получу при отображении конкретное название в title
--
Отправлено из Mail.ru для Android четверг, 28 января 2021г., 16:43 +03:00 от Valery Pavlikov  notifications@github.com :

>@Vokler requested changes on this pull request.
>----------------------------------------------------------------------
>In  mainapp/views.py :
>      context = {
>-        'title': 'каталог',
>-        'products': products_data
>+        'products': Product.objects.all(),
>+        'categories': ProductCategory.objects.all(),
>+        'title': 'каталог'
>+    }
>+    return render(request, 'mainapp/products.html', context)
>+
>+
>+def category(request, pk):
>+    context = {
>+        'products': Product.objects.filter(category=pk),
>+        'categories': ProductCategory.objects.all(),
>+        'title': ProductCategory.objects.get(pk=pk)
>
>А почему у вас title - это объект из модели?)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-01-28 13:56 UTC, kostenkoSergei commented
У меня уже в в шаблоне для отображения каталога прописаны ссылки для категорий, при нажатии вызывается вьюха category и получаем страницу, в title которой видим нашу конкретную категорию, на которую нажали
--
Отправлено из Mail.ru для Android четверг, 28 января 2021г., 16:43 +03:00 от Valery Pavlikov  notifications@github.com :

>@Vokler requested changes on this pull request.
>----------------------------------------------------------------------
>In  mainapp/views.py :
>      context = {
>-        'title': 'каталог',
>-        'products': products_data
>+        'products': Product.objects.all(),
>+        'categories': ProductCategory.objects.all(),
>+        'title': 'каталог'
>+    }
>+    return render(request, 'mainapp/products.html', context)
>+
>+
>+def category(request, pk):
>+    context = {
>+        'products': Product.objects.filter(category=pk),
>+        'categories': ProductCategory.objects.all(),
>+        'title': ProductCategory.objects.get(pk=pk)
>
>А почему у вас title - это объект из модели?)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-01-29 09:08 UTC, Vokler approved these changes

2021-01-29 09:09 UTC, merged